name: sixam_mart_delivery
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  shared_preferences: ^2.5.4
  connectivity_plus: ^7.0.0
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  firebase_auth: ^6.1.3
  flutter_local_notifications: ^19.5.0
  path_provider: ^2.1.5
  pin_code_fields: ^8.0.1
  http: ^1.6.0
  flutter_switch: ^0.3.2
  shimmer_animation: ^2.2.2+1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.14.0
  url_launcher: ^6.3.2
  vibration: ^3.1.4
  image_picker: ^1.2.1
  phone_numbers_parser: ^9.0.17
  country_code_picker: ^3.4.1
  audioplayers: ^6.5.1
  flutter_widget_from_html_core: ^0.17.0
  cached_network_image: ^3.4.1
  path: ^1.9.1
  http_parser: ^4.1.2
  intl: ^0.20.2
  dotted_border: ^3.1.0
  photo_view: ^0.15.0
  web_socket_channel: ^3.0.3
  flutter_inappwebview: ^6.1.5
  just_the_tooltip: ^0.0.12
  flutter_svg: ^2.2.3
  permission_handler: ^12.0.1
  flutter_foreground_task: ^9.1.0
  dropdown_button2: ^2.3.9
  open_file: ^3.5.10
  carousel_slider: ^5.1.1
  share_plus: ^12.0.1
  fluttertoast: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900